DROP TABLE MEMBER;

CREATE TABLE MEMBER
(
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(32) NOT NULL UNIQUE,
    PW VARCHAR2(64) NOT NULL,
    NAME VARCHAR2(64),
    PHONE VARCHAR2(100),
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    ADDRESS VARCHAR2(200),
    REGDATE DATE,
    STATUS VARCHAR2(32)
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
